version: "3.9"

services:

  db:
    image: postgres:15
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wiki_db
      - POSTGRES_USER=wiki_user
      - POSTGRES_PASSWORD=wiki_password
    env_file:
      - ./.env

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn WIKISite.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: