# Generated by Django 4.1.5 on 2023-01-04 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Content', '0003_commentmodel_postsmodel_delete_mediacontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
        migrations.AlterModelOptions(
            name='postsmodel',
            options={'verbose_name': 'Post'},
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_for_comment', to='Content.postsmodel'),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_for_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
