# Generated by Django 4.1.5 on 2023-01-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_commentsmodel_alter_postsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='media',
            field=models.ImageField(default='', upload_to='static/media/content'),
        ),
    ]
