# Generated by Django 4.1.5 on 2023-01-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_postsmodel_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='media',
            field=models.ImageField(default='', null=True, upload_to='static/media/content'),
        ),
    ]
