# Generated by Django 4.1.5 on 2023-01-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0007_alter_postsmodel_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='media',
            field=models.ImageField(blank=True, default='', upload_to='../static/media/content'),
        ),
    ]
