# Generated by Django 4.1.5 on 2023-01-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0009_alter_postsmodel_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_phrase', models.CharField(max_length=255)),
            ],
        ),
    ]
