# Generated by Django 4.1.5 on 2023-01-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0010_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description_site',
            field=models.TextField(default=''),
        ),
    ]
