# Generated by Django 4.1.5 on 2023-01-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0011_settings_description_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
    ]
