# Generated by Django 4.1.5 on 2023-01-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0012_postsmodel_count_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active')], default='pending', max_length=255),
        ),
    ]
