# Generated by Django 4.1.5 on 2023-01-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0013_postsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='single_page_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
