# Generated by Django 4.1.5 on 2023-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0014_settings_single_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='footer_text',
            field=models.TextField(default=''),
        ),
    ]
