# Generated by Django 4.1.5 on 2023-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0015_settings_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='update',
            field=models.CharField(default='', max_length=255),
        ),
    ]
