# Generated by Django 4.1.5 on 2023-01-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0017_alter_postsmodel_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='developers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='game_modes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='genres',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='platforms',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='publishers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='release_dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
