# Generated by Django 4.1.5 on 2023-01-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0018_postsmodel_developers_postsmodel_game_modes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsmodel',
            old_name='media',
            new_name='media_main_post',
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='media_sidebar',
            field=models.ImageField(blank=True, default='', upload_to='content'),
        ),
    ]
