# Generated by Django 4.1.5 on 2023-01-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0019_rename_media_postsmodel_media_main_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='message',
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='base',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='gameplay',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='growth',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='latest_update',
            field=models.TextField(blank=True, default=''),
        ),
    ]
