# Generated by Django 4.1.5 on 2023-01-23 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Content', '0020_remove_postsmodel_message_postsmodel_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsmodel',
            old_name='timestamps',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='postsmodel',
            name='update',
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='genres',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
