# Generated by Django 4.1.5 on 2023-01-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0021_rename_timestamps_postsmodel_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='single_page_title',
        ),
    ]
